const axios = require("axios");

let fontEnabled = true;

function formatFont(text) {
  const fontMapping = {
    a: "𝖺", b: "𝖻", c: "𝖼", d: "𝖽", e: "𝖾", f: "𝖿", g: "𝗀", h: "𝗁", i: "𝗂", j: "𝗃", k: "𝗄", l: "𝗅", m: "𝗆",
    n: "𝗇", o: "𝗈", p: "𝗉", q: "𝗊", r: "𝗋", s: "𝗌", t: "𝗍", u: "𝗎", v: "𝗏", w: "𝗐", x: "𝗑", y: "𝗒", z: "𝗓",
    A: "𝖠", B: "𝖡", C: "𝖢", D: "𝖣", E: "𝖤", F: "𝖥", G: "𝖦", H: "𝖧", I: "𝖨", J: "𝖩", K: "𝖪", L: "𝖫", M: "𝖬",
    N: "𝖭", O: "𝖮", P: "𝖯", Q: "𝖰", R: "𝖱", S: "𝖲", T: "𝖳", U: "𝖴", V: "𝖵", W: "𝖶", X: "𝖷", Y: "𝖸", Z: "𝖹"
  };

  let formattedText = "";
  for (const char of text) {
    formattedText += fontEnabled && fontMapping[char] ? fontMapping[char] : char;
  }
  return formattedText;
}

const birdFacts = [
  "Owls can rotate their necks 270 degrees.",
  "Hummingbirds are the only birds that can fly backwards.",
  "A group of flamingos is called a flamboyance.",
  "Penguins propose to their mates with a pebble.",
  "Some ducks sleep with one eye open.",
  "Pigeons can recognize themselves in mirrors.",
  "The fastest bird is the peregrine falcon, reaching speeds over 240 mph.",
  "Male emperor penguins incubate eggs by balancing them on their feet.",
  "Woodpeckers can peck up to 20 times per second.",
  "Parrots can live for over 60 years.",
  "Birds are descendants of dinosaurs.",
  "Kiwi birds are blind and hunt by smell.",
  "Birds have hollow bones to help them fly.",
  "The lyrebird can mimic almost any sound it hears.",
  "Crows are highly intelligent and can solve complex puzzles.",
  "Seagulls can drink seawater.",
  "Some bird species mate for life.",
  "The smallest bird is the bee hummingbird.",
  "Ostriches have the largest eyes of any land animal.",
  "The albatross can sleep while flying.",
  "Chickens can remember over 100 faces.",
  "Cardinals like to cover themselves in ants.",
  "Eagles have vision up to 8 times stronger than humans.",
  "Robins are territorial and aggressive to other robins.",
  "Roadrunners can sprint up to 20 mph.",
  "Swifts can stay airborne for 10 months without landing.",
  "Puffins use their beaks to carry up to 10 fish at once.",
  "Birds don't urinate — they excrete uric acid.",
  "Some birds like ravens can play games.",
  "The Arctic tern migrates over 40,000 miles each year.",
  "Birds can see ultraviolet light.",
  "Many birds use stars to navigate.",
  "Peacocks fan their tail feathers to impress females.",
  "Chickadees store food in hundreds of hiding spots.",
  "The hoatzin bird ferments food like a cow.",
  "Flamingos get their pink color from their diet.",
  "Some birds sleep while perched without falling.",
  "Vultures can eat rotting meat without getting sick.",
  "Male birds often sing to attract mates.",
  "Birds preen to maintain their feathers.",
  "The secretary bird kills snakes by stomping on them.",
  "Hornbills seal themselves in tree cavities when nesting.",
  "The shoebill stork has a terrifying stare.",
  "Ducks have waterproof feathers.",
  "Birds have excellent color vision.",
  "The kakapo is a flightless nocturnal parrot.",
  "Swans can break a human’s arm with their wings.",
  "Macaws can crack nuts with 500 psi of pressure.",
  "The nightjar’s camouflage makes it nearly invisible.",
  "Birds communicate with songs, dances, and calls."   "Owls can rotate their necks 270 degrees.",
  "Hummingbirds are the only birds that can fly backwards.",
  "A group of flamingos is called a flamboyance.",
  "Penguins propose to their mates with a pebble.",
  "Some ducks sleep with one eye open.",
  "Pigeons can recognize themselves in mirrors.",
  "The fastest bird is the peregrine falcon, reaching speeds over 240 mph.",
  "Male emperor penguins incubate eggs by balancing them on their feet.",
  "Woodpeckers can peck up to 20 times per second.",
  "Parrots can live for over 60 years.",
  "Birds are descendants of dinosaurs.",
  "Kiwi birds are blind and hunt by smell.",
  "Birds have hollow bones to help them fly.",
  "The lyrebird can mimic almost any sound it hears.",
  "Crows are highly intelligent and can solve complex puzzles.",
  "Seagulls can drink seawater.",
  "Some bird species mate for life.",
  "The smallest bird is the bee hummingbird.",
  "Ostriches have the largest eyes of any land animal.",
  "The albatross can sleep while flying.",
  "Chickens can remember over 100 faces.",
  "Cardinals like to cover themselves in ants.",
  "Eagles have vision up to 8 times stronger than humans.",
  "Robins are territorial and aggressive to other robins.",
  "Roadrunners can sprint up to 20 mph.",
  "Swifts can stay airborne for 10 months without landing.",
  "Puffins use their beaks to carry up to 10 fish at once.",
  "Birds don't urinate — they excrete uric acid.",
  "Some birds like ravens can play games.",
  "The Arctic tern migrates over 40,000 miles each year.",
  "Birds can see ultraviolet light.",
  "Many birds use stars to navigate.",
  "Peacocks fan their tail feathers to impress females.",
  "Chickadees store food in hundreds of hiding spots.",
  "The hoatzin bird ferments food like a cow.",
  "Flamingos get their pink color from their diet.",
  "Some birds sleep while perched without falling.",
  "Vultures can eat rotting meat without getting sick.",
  "Male birds often sing to attract mates.",
  "Birds preen to maintain their feathers.",
  "The secretary bird kills snakes by stomping on them.",
  "Hornbills seal themselves in tree cavities when nesting.", [
  "The male frigatebird inflates a red throat pouch to attract females.",
  "Hoopoes use their uropygial gland to produce a foul-smelling secretion.",
  "The common poorwill is the only bird known to hibernate.",
  "The long-tailed widowbird uses its extended tail to court mates.",
  "Australian magpies are known for their complex vocalizations.",
  "The resplendent quetzal is sacred in many Mesoamerican cultures.",
  "The helmeted hornbill has a solid casque used in aerial battles.",
  "Barn swallows build mud nests under bridges and eaves.",
  "The Indian peafowl can shake its feathers 26 times per second.",
  "The white-throated sparrow has two color morphs with different behaviors.",
  "The Clark’s nutcracker can hide 30,000 seeds in a season.",
  "Mynah birds can imitate human speech better than some parrots.",
  "The African jacana is nicknamed the ‘Jesus bird’ for walking on water lilies.",
  "The tawny frogmouth is often mistaken for an owl.",
  "The shoebill’s call sounds like a machine gun.",
  "The king of saxony bird-of-paradise has ribbon-like head feathers.",
  "The American woodcock has a spiral courtship flight.",
  "The bearded vulture dyes its feathers with iron oxide.",
  "The great potoo uses incredible camouflage and stillness.",
  "The Andean condor is one of the largest flying birds by wingspan.",
  "Some species of grebes eat their own feathers.",
  "The cuckoo chick ejects other eggs from the nest after hatching.",
  "The common loon’s haunting call is a symbol of the wilderness.",
  "The red-winged blackbird aggressively defends its nesting area.",
  "The lyrebird can mimic camera shutters and chainsaws.",
  "Some parrots give themselves names by mimicking sounds uniquely.",
  "The red avadavat is also called the strawberry finch.",
  "Birds have a unique bone called a furcula, or wishbone.",
  "The violet-backed starling is one of the most vividly colored birds.",
  "Some owls use their facial discs to funnel sound to their ears.",
  "The oilbird lives in caves and uses echolocation.",
  "The sandgrouse carries water in its breast feathers.",
  "The northern cardinal sings duets with its mate.",
  "The brush turkey builds compost mound nests.",
  "The snowy owl hunts during the day unlike most owls.",
  "The black-capped chickadee adds and drops flock members seasonally.",
  "Some hummingbirds go into torpor to conserve energy.",
  "The wattled crane has one of the slowest reproductive rates.",
  "The goliath heron is the largest heron species.",
  "The violet turaco has crimson flight feathers.",
  "Some finches use tools to scratch their heads.",
  "The antbird follows army ants to feed on fleeing insects.",
  "Many bird species molt their feathers after breeding season.",
  "The superb fairywren presents flower petals during courtship.",
  "The crested auklet produces a citrus-like smell.",
  "Some ducks have corkscrew-shaped reproductive organs.",
  "The Egyptian vulture uses tools to crack open eggs.",
  "The male satin bowerbird collects blue objects to attract mates.",
  "Snow buntings breed in the Arctic and migrate south in winter.",
  "The southern ground hornbill lives up to 60 years.",
  "The red-billed oxpecker eats parasites off large mammals.",
  "The American kestrel is North America’s smallest falcon.",
  "Birds use their third eyelid (nictitating membrane) to protect their eyes.",
  "The galah cockatoo is known for its playful behavior.",
  "The green heron uses bait to fish — a rare example of tool use.",
  "Some birds dance in rain puddles during courtship.",
  "The nene is Hawaii’s state bird and is endangered.",
  "Whip-poor-wills are named after their continuous call.",
  "The rainbow lorikeet feeds on nectar and pollen.",
  "Kittiwakes nest on vertical cliffs near the ocean.",
  "The Eurasian wryneck can twist its neck like a snake.",
  "The marabou stork is known as the ‘undertaker bird’.",
  "The secretarybird uses high jumps to kill prey like snakes.",
  "The red-knobbed coot builds floating nests.",
  "Birds can move each feather individually using muscles.",
  "The grey go-away-bird got its name from its call.",
  "Some kingfishers nest in termite mounds.",
  "The kakariki is a fast-flying New Zealand parakeet.",
  "The blue jay mimics hawk calls to scare other birds.",
  "Sunbitterns spread their wings to display eye spots.",
  "The white tern lays its egg on bare tree branches.",
  "The Japanese crane dances as part of mating rituals.",
  "The horned lark sings while performing flight displays.",
  "Many seabirds can drink salt water using special glands.",
  "Birds’ hearts beat much faster than humans — up to 1200 bpm.",
  "The Andean cock-of-the-rock has a unique fan-shaped crest.",
  "Birds have more bones in their necks than giraffes.",
  "Some parrots grind their beaks to show contentment.",
  "The red-tailed hawk screech is often used in movies.",
  "Some raptors see 5 times more detail than humans.",
  "Budgies are the third most popular pet in the world.",
  "The paradise flycatcher has an extremely long tail.",
  "The turaco has unique copper-based green pigment in feathers.",
  "The ibis uses its long beak to probe in mud.",
  "The golden eagle can take down animals as large as deer.",
  "The pygmy owl mimics songbird calls to lure prey.",
  "The swan song myth has no biological basis.",
  "Birds evolved from theropod dinosaurs like Velociraptor.",
  "The collared pratincole can catch insects mid-air.",
  "Many birds use alarm calls that are species-specific.",
  "The great tit can distinguish individual human faces.",
  "Potoos freeze in place to blend in with tree branches.",
  "Greater sage-grouse males perform booming displays.",
  "Some birds sleep while flying during migration.",
  "The golden pheasant is known for its bright, golden head.",
  "The long-eared owl has asymmetrical ears for precise hearing.",
  "The lappet-faced vulture dominates other scavengers.",
  "The cassowary has dagger-like claws on its feet.",
  "Birds have highly efficient respiratory systems.",
  "Some geese migrate in family groups.",
  "Boobies were named for their apparent lack of fear.",
  "The Amazonian royal flycatcher raises a bright crest.",
  "Some birds such as the corncrake are rarely seen but often heard.",
  "The wallcreeper climbs vertical rock faces in search of insects.",
  "Birds can sense Earth's magnetic field through magnetoreception.",
  "Male golden-collared manakins use wing snaps in mating dances.",
  "Birds can produce two different sounds simultaneously.",
  "Many birds time nesting to coincide with insect abundance.",
  "Some hummingbirds defend flower patches aggressively.",
  "The flame bowerbird creates flame-colored bowers.",
  "The red-legged seriema uses rocks to kill prey.",
  "Some birds mimic predators to protect their nests.",
  "The thick-knee bird has large yellow eyes adapted for night.",
  "The greater roadrunner can kill rattlesnakes.",
  "The green woodpecker eats mainly ants.",
  "The pied kingfisher hovers before diving for fish.",
  "Birds fluff feathers to regulate temperature.",
  "The wattled starling forms large breeding colonies.",
  "The snowy egret uses its bright feet to attract fish.",
  "Birds regulate flight using their alula (thumb feather).",
  "The northern shrike impales prey on thorns.",
  "The horned guan has a red horn-like structure on its head.",
  "The umbrellabird has a large inflatable throat wattle." 
  "The shoebill stork has a terrifying stare.",
  "Ducks have waterproof feathers.",
  "Birds have excellent color vision.",
  "The kakapo is a flightless nocturnal parrot.",
  "Swans can break a human’s arm with their wings.",
  "Macaws can crack nuts with 500 psi of pressure.",
  "The nightjar’s camouflage makes it nearly invisible.",
  "Birds communicate with songs, dances, and calls.", "Owls can rotate their necks up to 270 degrees.",
"Hummingbirds are the only birds that can fly backwards.",
"A group of flamingos is called a flamboyance.",
"Penguins propose to their mates with a pebble.",
"Some ducks sleep with one eye open.",
"Pigeons can recognize themselves in mirrors.",
"The peregrine falcon is the fastest bird, reaching over 240 mph.",
"Male emperor penguins incubate eggs on their feet.",
"Woodpeckers can peck 20 times per second.",
"Parrots can live more than 60 years.",
"Birds are the closest living relatives of dinosaurs.",
"Kiwi birds are blind and use smell to navigate.",
"Birds have hollow bones to reduce weight for flight.",
"The lyrebird can mimic chainsaws and camera shutters.",
"Crows can recognize human faces and hold grudges.",
"Seagulls can drink saltwater safely.",
"Some bird species mate for life, like swans.",
"The bee hummingbird is the smallest bird in the world.",
"Ostriches have the largest eyes of any land animal.",
"Albatrosses can sleep while flying.",
"Chickens remember over 100 individual faces.",
"Cardinals cover themselves in ants—a behavior called anting.",
"Eagles have vision eight times sharper than humans.",
"Robins fiercely defend their territory.",
"Roadrunners can sprint up to 20 miles per hour.",
"Swifts can stay airborne for up to 10 months.",
"Puffins can carry multiple fish in their beaks at once.",
"Birds excrete uric acid instead of urine.",
"Ravens are known to play games and mimic sounds.",
"Arctic terns migrate up to 40,000 miles annually.",
"Birds can see ultraviolet light.",
"Many migratory birds use the stars to navigate.",
"Peacocks spread their feathers to attract mates.",
"Chickadees hide food in hundreds of locations.",
"The hoatzin bird digests food by fermentation.",
"Flamingos are pink due to the shrimp they eat.",
"Some birds sleep while perched without falling.",
"Vultures can safely eat diseased carrion.",
"Male birds sing to defend territory and attract mates.",
"Preening helps birds maintain feather health.",
"The secretary bird kills snakes by stomping.",
"Hornbills seal themselves inside tree nests.",
"The shoebill stork has a prehistoric look.",
"Ducks have oil glands that waterproof their feathers.",
"Birds have tetrachromatic vision—four types of cones.",
"The kakapo is a flightless nocturnal parrot.",
"Swans can be very aggressive in defense.",
"Macaws can crack nuts with powerful beaks.",
"The nightjar is a master of camouflage.",
"Birds use complex calls to communicate danger.",
"Pelicans have expandable throat pouches.",
"Some birds tap rhythms to communicate.",
"The wandering albatross has a wingspan up to 12 feet.",
"Kingfishers dive headfirst to catch prey.",
"Ravens can imitate human speech.",
"Birds groom each other in a behavior called allopreening.",
"Male bowerbirds decorate nests to impress females.",
"The kiwi lays the largest egg relative to its body.",
"Birds molt feathers to replace old ones.",
"Flamingos often stand on one leg.",
"The cassowary is considered the most dangerous bird.",
"Birds sing more frequently in the morning.",
"Chickens communicate using over 30 different sounds.",
"A hummingbird's wings beat up to 80 times per second.",
"Parrots can solve logic puzzles.",
"The African grey parrot is known for its vocabulary.",
"Some birds fly in a V formation to save energy.",
"Owls are virtually silent in flight.",
"The barn owl is found on every continent except Antarctica.",
"Birds have no bladder and conserve water by excreting urates.",
"The harpy eagle has claws as long as a grizzly bear’s.",
"Swallows return to the same nesting site each year.",
"Cuckoos lay their eggs in other birds’ nests.",
"The male lyrebird can mimic 20 different bird calls.",
"Birds pant to cool themselves since they don't sweat.",
"Many birds puff up to stay warm.",
"Woodpeckers have shock-absorbing skulls.",
"Some songbirds learn tunes from adult mentors.",
"Birds often use the sun to orient themselves.",
"The loon has solid bones to help it dive.",
"The American goldfinch molts twice a year.",
"Some birds form crèches to protect young together.",
"The wandering tattler got its name from its call.",
"Birds may fake injuries to distract predators from nests.",
"Many birds prefer to bathe in dust to remove parasites.",
"The toucan’s bill helps it regulate temperature.",
"Birds clean their beaks by wiping them on branches.",
"The great horned owl can crush prey with 500 psi.",
"The weaverbird builds intricate hanging nests.",
"Birds use sunbathing to control parasites.",
"Starlings can mimic car alarms and ringtones.",
"The European robin is a symbol of Christmas.",
"Lovebirds got their name from sitting close together.",
"Birds sometimes migrate at night.",
"Some birds drop shells to crack them open.",
"A shoebill’s bill can decapitate prey instantly.",
"Birds see faster than humans, detecting flickers up to 100 Hz.", 
"The oilbird uses echolocation in the dark.",
"The acorn woodpecker stores thousands of acorns in trees.",
"The rhea is a flightless bird native to South America.",
"The jacana bird walks on lily pads thanks to long toes.",
"Mockingbirds can memorize over 200 songs.",
"Storks are monogamous and return to the same mate yearly.",
"Birds use their tails for steering during flight.",
"The keel-billed toucan's beak is lightweight and hollow.",
"Some birds migrate thousands of miles without stopping." "The male emu takes care of the eggs and chicks after the female lays them.",
"The harlequin duck is known for its vibrant plumage and love of fast-flowing streams.",
"The red-faced cormorant nests on steep cliffs along rocky coasts.",
"The black skimmer feeds by skimming the water surface with its lower beak.",
"The secretary bird walks up to 20 km a day hunting on foot.",
"The Philippine eagle is one of the rarest and most powerful birds of prey.",
"The Nicobar pigeon is the closest living relative to the extinct dodo.",
"The male greater prairie chicken performs a booming sound during mating displays.",
"The male white bellbird has the loudest call of any bird.",
"The dusky lory feeds on nectar and pollen using a brush-tipped tongue.",
"The Wilson's storm-petrel is one of the most abundant bird species in the world.",
"The common blackbird is known for its melodious song, especially at dawn.",
"The rufous hornero builds clay oven-like nests on trees or poles.",
"The helmeted guineafowl is native to Africa and has a bony casque on its head.",
"The blue-capped cordon-bleu performs a tap-dancing-like courtship.",
"The European bee-eater catches insects midair and hits them on branches.",
"The white-throated needletail is among the fastest flying birds in level flight.",
"The bristle-thighed curlew uses tools to break open seabird eggs.",
"The elegant trogon is Arizona’s only regularly nesting trogon species.",
"The spectacled eider dives deep to find mollusks on the sea floor.",
"The American dipper can walk underwater against strong currents.",
"The great green macaw is critically endangered due to habitat loss.",
"The guira cuckoo lives communally in South American savannas.",
"The northern gannet dives from 100 feet to catch fish underwater.",
"The tawny owl is highly territorial and active mostly at night.",
"The orange-bellied parrot is one of the world’s rarest parrots.",
"The reed warbler is a common host of the parasitic cuckoo.",
"The little bustard performs a leaping display during breeding season.",
"The crimson sunbird is often mistaken for a hummingbird.",
"The Inca tern has a stylish mustache of white feathers.",
"The Eurasian hoopoe fans its crest when alarmed or excited.",
"The streak-throated woodpecker is common in the Indian subcontinent.",
"The jungle babbler is called 'seven sisters' due to its gregarious nature.",
"The red-crested turaco has striking red wing feathers visible only in flight.",
"The white-rumped shama is a skilled mimic and kept as a songbird in Asia.",
"The northern pintail migrates thousands of kilometers yearly.",
"The Eurasian eagle-owl has ear tufts that help with camouflage.",
"The white stork is associated with myths about delivering babies.",
"The black vulture often scavenges in groups with communal roosting.",
"The bearded barbet has a brush-like tongue for feeding on fruit.",
"The Asian koel lays its eggs in crow nests to avoid parenting.",
"The zebra dove makes a pleasant, soft cooing sound.",
"The red-billed tropicbird has long tail streamers and nests on cliffs.",
"The violet-crowned hummingbird is found in arid scrub of Mexico and the U.S.",
"The Malabar whistling thrush is nicknamed the ‘whistling schoolboy’.",
"The white-bellied sea eagle preys on fish and waterbirds.",
"The bicolored wren is the largest wren species in South America.",
"The black drongo aggressively chases away larger birds.",
"The hoary redpoll survives Arctic winters by fluffing its feathers.",
"The common murre dives to over 100 meters to catch fish.",
"The green ibis is often seen in flooded forests and marshes.",
"The pied crow is one of the smartest birds in Africa.",
"The Sri Lanka blue magpie is endemic to the island’s rainforests.",
"The azure kingfisher lives near rivers and feeds on small fish.",
"The white-eyed vireo is often heard before it's seen.",
"The capercaillie males display dramatically in mating leks.",
"The bar-tailed godwit holds the record for longest non-stop migration.",
"The black-crowned night heron is most active at dusk and dawn.",
"The collared aracari is a small toucan with a large, colorful bill.",
"The ruddy turnstone flips over rocks to find invertebrates.",
"The bananaquit feeds on nectar using a curved beak.",
"The green bee-eater loves to sunbathe and dust-bathe.",
"The rufous treepie is part of the crow family and is very vocal.",
"The purple swamphen has long toes to walk on floating vegetation.",
"The ferruginous hawk is one of the largest buteos in North America.",
"The redstart fans its tail as part of its foraging behavior."
];

module.exports.config = {
  name: "birdfact",
  version: "1.0.0",
  role: 0,
  hasPrefix: true,
  aliases: [],
  description: "Get a random bird fact",
  usage: "birdfact",
  credits: "Developer",
  cooldown: 3,
};

module.exports.run = async function ({ api, event }) {
  const threadID = event.threadID;
  const messageID = event.messageID;

  const fact = birdFacts[Math.floor(Math.random() * birdFacts.length)];
  const message = `🐦 𝖱𝖺𝗇𝖽𝗈𝗆 𝖡𝗂𝗋𝖽 𝖥𝖺𝖼𝗍\n\n${fact}`;

  return api.sendMessage(formatFont(message), threadID, messageID);
};