const axios = require("axios");

let fontEnabled = true;

function formatFont(text) {
  const fontMapping = {
    a: "𝖺", b: "𝖻", c: "𝖼", d: "𝖽", e: "𝖾", f: "𝖿", g: "𝗀", h: "𝗁", i: "𝗂", j: "𝗃", k: "𝗄", l: "𝗅", m: "𝗆",
    n: "𝗇", o: "𝗈", p: "𝗉", q: "𝗊", r: "𝗋", s: "𝗌", t: "𝗍", u: "𝗎", v: "𝗏", w: "𝗐", x: "𝗑", y: "𝗒", z: "𝗓",
    A: "𝖠", B: "𝖡", C: "𝖢", D: "𝖣", E: "𝖤", F: "𝖥", G: "𝖦", H: "𝖧", I: "𝖨", J: "𝖩", K: "𝖪", L: "𝖫", M: "𝖬",
    N: "𝖭", O: "𝖮", P: "𝖯", Q: "𝖰", R: "𝖱", S: "𝖲", T: "𝖳", U: "𝖴", V: "𝖵", W: "𝖶", X: "𝖷", Y: "𝖸", Z: "𝖹"
  };

  let formattedText = "";
  for (const char of text) {
    formattedText += fontEnabled && fontMapping[char] ? fontMapping[char] : char;
  }
  return formattedText;
}

module.exports.config = {
  name: "right",
  version: "1.0.0",
  role: 0,
  hasPrefix: true,
  aliases: ["humanright"],
  description: "Fetch a random human right",
  usage: "right",
  credits: "right",
  cooldown: 3,
};

module.exports.run = async function ({ api, event }) {
  const { threadID, messageID } = event;

  await api.sendMessage(formatFont("🕊️ Fetching a human right..."), threadID, messageID);

  const humanRights = [
    "Right to life",
    "Right to education",
    "Right to privacy",
    "Right to health care",
    "Right to clean water",
    "Right to free speech",
    "Right to vote",
    "Right to a fair trial",
    "Right to due process",
    "Right to freedom of religion",
    "Right to freedom of movement",
    "Right to seek asylum",
    "Right to be free from torture",
    "Right to marry and form a family",
    "Right to work",
    "Right to equal pay for equal work",
    "Right to rest and leisure",
    "Right to nationality",
    "Right to own property",
    "Right to participate in cultural life",
    "Right to be presumed innocent",
    "Right to education in own language",
    "Right to digital privacy",
    "Right to protest",
    "Right to access information",
    "Right to legal representation",
    "Right to shelter",
    "Right to food",
    "Right to social security",
    "Right to freedom from discrimination",
    "Right to mental health support",
    "Right to disability inclusion",
    "Right to vote in local elections",
    "Right to clean air",
    "Right to freely choose employment",
    "Right to express gender identity",
    "Right to sexual orientation freedom",
    "Right to freedom from slavery",
    "Right to protection from child labor",
    "Right to safe workplace",
    "Right to environmental protection",
    "Right to a healthy climate",
    "Right to access technology",
    "Right to academic freedom",
    "Right to digital literacy",
    "Right to participate in government",
    "Right to a safe home",
    "Right to emergency assistance",
    "Right to peaceful assembly",
    "Right to humanitarian aid",
    "Right to internet access",
    "Right to religious conversion",
    "Right to science and invention",
    "Right to play (children)",
    "Right to equal marriage",
    "Right to protection from domestic violence",
    "Right to nonbinary recognition",
    "Right to clean sanitation",
    "Right to safe migration",
    "Right to fair immigration procedures",
    "Right to cultural preservation",
    "Right to use one's native language",
    "Right to a decent standard of living",
    "Right to early childhood care",
    "Right to retirement support",
    "Right to bodily autonomy",
    "Right to emergency healthcare",
    "Right to vote by mail",
    "Right to freedom of thought",
    "Right to public transportation",
    "Right to energy access",
    "Right to financial services",
    "Right to protection from cyberbullying",
    "Right to digital identity",
    "Right to be forgotten online",
    "Right to open data",
    "Right to vaccine access",
    "Right to cultural exchange",
    "Right to affordable housing",
    "Right to be free from police brutality",
    "Right to learning materials",
    "Right to legal aid",
    "Right to identity documents",
    "Right to prison reform",
    "Right to gender-neutral bathrooms",
    "Right to participate in sports",
    "Right to language translation in court",
    "Right to vote without ID barriers",
    "Right to abortion (in some regions)",
    "Right to science-based education",
    "Right to accessible websites",
    "Right to refugee protection",
    "Right to safety from hate speech",
    "Right to public health data",
    "Right to online anonymity",
    "Right to low-cost medicine",
    "Right to menstrual health support",
    "Right to paternity leave",
    "Right to disability-friendly transport",
    "Right to rebuild after disasters",
    "Right to compensation for injury",
    "Right to human dignity",
    "Right to nonviolence",
    "Right to online education",
    "Right to sustainable development",
    "Right to water during droughts",
    "Right to indigenous land rights",
    "Right to youth representation",
    "Right to freelance protections",
    "Right to cryptocurrency use (debated)",
    "Right to blockchain privacy",
    "Right to AI transparency",
    "Right to fair algorithms",
    "Right to ethical AI",
    "Right to climate justice",
    "Right to trial in own language",
    "Right to elder care",
    "Right to be free from harassment",
    "Right to reproductive health",
    "Right to non-censorship",
    "Right to affordable childcare",
    "Right to knowledge access",
    "Right to choose school system",
    "Right to non-automated firing",
    "Right to digital repair",
    "Right to restore name/gender",
    "Right to ancestral land",
    "Right to birth registration",
    "Right to death with dignity",
    "Right to media plurality",
    "Right to challenge government",
    "Right to criticise leaders",
    "Right to travel freely",
    "Right to freedom from poverty",
    "Right to public parks",
    "Right to data ownership",
    "Right to nonviolence education",
    "Right to fair content moderation",
    "Right to energy-efficient housing",
    "Right to peace education",
    "Right to cross-border family unity",
    "Right to post-prison rehabilitation",
    "Right to gender equality in hiring",
    "Right to access public meetings",
    "Right to be heard",
    "Right to nondiscriminatory algorithms",
    "Right to language accessibility",
    "Right to cooperative labor",
    "Right to digital democracy",
    "Right to future generations' rights",
    "Right to fair copyright laws",
    "Right to eco-friendly burial",
    "Right to mindful technology use",
    "Right to human-AI interaction norms",
    "Right to parental leave",
    "Right to be safe online",
    "Right to humane prisons",
    "Right to defend against surveillance",
    "Right to community land",
    "Right to digital contracts",
    "Right to climate migration",
    "Right to emotional safety",
    "Right to public expression",
    "Right to reparations",
    "Right to AI explanation",
    "Right to cultural property",
    "Right to educational equity",
    "Right to zero discrimination",
    "Right to algorithmic transparency",
    "Right to public archives",
    "Right to environmental education",
    "Right to land protection",
    "Right to ethical labor",
    "Right to green jobs",
    "Right to creative freedom",
    "Right to social participation",
    "Right to telehealth access",
    "Right to digital consent",
    "Right to peaceful resistance",
    "Right to future literacy",
    "Right to protect whistleblowers",
    "Right to safe roads",
    "Right to ethical research",
    "Right to protect species",
    "Right to disaster risk knowledge",
    "Right to algorithm-free zones",
    "Right to preserve traditions",
    "Right to open science",
    "Right to zero-waste cities",
    "Right to non-toxic housing",
    "Right to silent protest",
    "Right to AI-free jobs",
    "Right to be digitally invisible",
    "Right to reclaim identity",
    "Right to neurodiverse inclusion",
    "Right to solidarity economies"
  ];

  const randomRight = humanRights[Math.floor(Math.random() * humanRights.length)];

  return api.sendMessage(
    formatFont(`🧾 𝗛𝗎𝗆𝖺𝗇 𝗥𝗂𝗀𝗁𝗍:\n\n${randomRight}`),
    threadID,
    messageID
  );
};